#### Fucntional Programming

#### numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)
- 주어진 축을 따라 1차원 슬라이스에 함수를 적용
- func1d(a, *args, **kwargs)를 실행하고, func1d는 1차원 배열에서 연산을 수행한다.
- 아래의 두 식과 동일하지만, 연산 시간은 더 빠르다.

In [ ]:
Ni, Nk = a.shape[:axis], a.shape[axis+1:]
for ii in ndindex(Ni):
    for kk in ndindex(Nk):
        f = func1d(arr[ii + s_[:,] + kk])
        Nj = f.shape
        for jj in ndindex(Nj):
            out[ii + jj + kk] = f[jj]

for ii in ndindex(Ni):
    for kk in ndindex(Nk):
        out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] + kk])

In [2]:
import numpy as np

def my_func(a):
    """Average first and last element of a 1-D array"""
    return (a[0] + a[-1]) * 0.5

b = np.array([[1,2,3], 
              [4,5,6],
              [7,8,9]])
print(np.apply_along_axis(my_func, 0, b)) # ↓
print(np.apply_along_axis(my_func, 1, b)) # →

[4. 5. 6.]
[2. 5. 8.]


In [3]:
b = np.array([[8,1,7],
              [4,3,9],
              [5,2,6]])
              
print(np.apply_along_axis(sorted, 0, b))
print(np.apply_along_axis(sorted, 1, b))

[[4 1 6]
 [5 2 7]
 [8 3 9]]
[[1 7 8]
 [3 4 9]
 [2 5 6]]


In [5]:
b = np.array([[8,1,7],
              [4,3,9],
              [5,2,6]])

print(np.apply_along_axis(np.diag, -1, b))
# array([[[1, 0, 0],
#         [0, 2, 0],
#         [0, 0, 3]],
#        [[4, 0, 0],
#         [0, 5, 0],
#         [0, 0, 6]],
#        [[7, 0, 0],
#         [0, 8, 0],
#         [0, 0, 9]]])

[[[8 0 0]
  [0 1 0]
  [0 0 7]]

 [[4 0 0]
  [0 3 0]
  [0 0 9]]

 [[5 0 0]
  [0 2 0]
  [0 0 6]]]
