### numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
- n : 값의 차이를 발생 시키는 간격

In [9]:
import numpy as np
x = np.array([1, 2, 4, 7, 0])
r = np.diff(x)
print(r) # [ 1  2  3 -7]

r = np.diff(x, n=2) 
print(r)
# 본인은 위의 결과가 간격을 2로 두어 [3(4-1의 결과), 5(7-2의 결과), -4(0-4의 결과)] --> [3, 5, -4] 가 나온다고 생각하였다.
# 하지만, 실제 연산 결과는 n=1 즉, 1차 차분 결과를 한번 더 차분한다.
# [1(2-1의 결과), 1(3-2의 결과), -10(-7)] -->[1, 1, -10]

r = np.diff(x, n=3) 
print(r) # 2차 차분 결과를 한번 더 차분한다.

r = np.diff(x, n=4) 
print(r)

r = np.diff(x, n=5) # 더이상 차분할 게 없으면, 에러 대신 빈 값을 반환한다.
print(r)

r = np.diff(x, n=6) 
print(r)

r = np.diff(x, n=0)
print(r)

[ 1  2  3 -7]
[  1   1 -10]
[  0 -11]
[-11]
[]
[]
[1 2 4 7 0]
